"""empty message

Revision ID: 1b450e3296f1
Revises: 847eea937baf
Create Date: 2018-11-12 01:01:57.677342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b450e3296f1'
down_revision = '847eea937baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_SKU_name'), 'SKU', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SKU_name'), table_name='SKU')
    # ### end Alembic commands ###
