"""empty message

Revision ID: 36e7b0be9a01
Revises: 8d476971c377
Create Date: 2018-11-11 21:03:50.903279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e7b0be9a01'
down_revision = '8d476971c377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SKU', sa.Column('storage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SKU', 'storage', ['storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SKU', type_='foreignkey')
    op.drop_column('SKU', 'storage_id')
    # ### end Alembic commands ###
