"""empty message

Revision ID: 847eea937baf
Revises: 9377a624d5da
Create Date: 2018-11-12 00:53:55.361565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847eea937baf'
down_revision = '9377a624d5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SKU_order_line_id_fkey', 'SKU', type_='foreignkey')
    op.drop_constraint('SKU_storage_id_fkey', 'SKU', type_='foreignkey')
    op.drop_column('SKU', 'storage_id')
    op.drop_column('SKU', 'order_line_id')
    op.add_column('order_line', sa.Column('sku_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_line', 'SKU', ['sku_id'], ['id'])
    op.add_column('storage', sa.Column('sku_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'storage', 'SKU', ['sku_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_column('storage', 'sku_id')
    op.drop_constraint(None, 'order_line', type_='foreignkey')
    op.drop_column('order_line', 'sku_id')
    op.add_column('SKU', sa.Column('order_line_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('SKU', sa.Column('storage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('SKU_storage_id_fkey', 'SKU', 'storage', ['storage_id'], ['id'])
    op.create_foreign_key('SKU_order_line_id_fkey', 'SKU', 'order_line', ['order_line_id'], ['id'])
    # ### end Alembic commands ###
