"""empty message

Revision ID: 9377a624d5da
Revises: 36e7b0be9a01
Create Date: 2018-11-12 00:42:50.128416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9377a624d5da'
down_revision = '36e7b0be9a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SKU', sa.Column('order_line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SKU', 'order_line', ['order_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SKU', type_='foreignkey')
    op.drop_column('SKU', 'order_line_id')
    # ### end Alembic commands ###
